# Default values for helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: asia.gcr.io/silver-lead-205101/techotrix
  tag: latest
  pullPolicy: Always 

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
