apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: {{ include "helm-chart.fullname" . }}
spec:
 backend:
   serviceName: {{ include "helm-chart.fullname" . }}
   servicePort: {{ .Values.service.port }}
